### PR TITLE
Defer timer creation to DeviceSelfManagedIoInit callback

### LINKED ISSUE #41: Get rid of arbitrary 100ms wait for EvtSetBlackTimer
**Background**: The driver is currently having an rather arbitrary 100ms wait before calling the `EvtSetBlackTimer` timer callback to turn off the tail light when connecting a mouse. This is done to avoid sporadic `WdfIoTargetOpen failed 0xc000000e (STATUS_NO_SUCH_DEVICE)` errors mentioned in #40.

**Task**: Replace the arbitrary 100ms wait with a better and more robust synchronization mechanism. This will probably involve deferring timer startup until the driver is "ready", but I'm not quite sure when this is.

Related doc:
* KMDF scenario: [A User Plugs in a Device](https://learn.microsoft.com/en-us/windows-hardware/drivers/wdf/a-user-plugs-in-a-device)
* [Power-Up Sequence for a Function or Filter Driver](https://learn.microsoft.com/en-us/windows-hardware/drivers/wdf/power-up-sequence-for-a-function-or-filter-driver)

Ideas to investigate:
* [`WdfDeviceInitSetPnpPowerEventCallbacks`](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/wdfdevice/nf-wdfdevice-wdfdeviceinitsetpnppowereventcallbacks)
* [`DO_DEVICE_INITIALIZING`](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/ns-wdm-_device_object#do_device_initializing)
* [`IoRegisterPlugPlayNotification`](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-ioregisterplugplaynotification) . Toaster [sample](https://github.com/microsoft/Windows-driver-samples/blob/main/general/toaster/toastDrv/kmdf/toastmon/toastmon.c#L224)
* [Using Device Interfaces (WDF)
](https://learn.microsoft.com/en-us/windows-hardware/drivers/wdf/using-device-interfaces) - also mentions notification
*

### PR DESCRIPTION
**Pull request by forderud**
Fixes #41 by avoiding the need for an arbitrary 100ms wait. `DeviceSelfManagedIoInit` is selected since it's the last callback invoked before the device is operational according to [Power-Up Sequence for a Function or Filter Driver](https://learn.microsoft.com/en-us/windows-hardware/drivers/wdf/power-up-sequence-for-a-function-or-filter-driver)

### CODE REVIEW

**Review by ManOnTheMountainTech — COMMENTED** [review]
Why are you doing a solo return within a scope?

File: TailLight/device.cpp [hunk 1]
```diff
@@ -113,30 +147,6 @@ Routine Description:
         return status;
```
Comment (ManOnTheMountainTech) [inline TailLight/device.cpp:147]: This is the "solo return"

Comment (forderud) [reply TailLight/device.cpp:147]: `return status;` is here done if the `WmiInitialize` call fail. However, this code isn't changed in this PR so you don't need to bother about it.

**Comment by ManOnTheMountainTech** [comment]
I notice that subscopes are used a lot, like:

 

Function DoSomething() {

{

               DoThis();

}

{

               DoThat();

}

}

 

I have some theories, but why is the code like this?

**Comment by forderud** [comment]
> I notice that subscopes are used a lot, like: Function DoSomething() { { DoThis(); } { DoThat(); } } I have some theories, but why is the code like this?

I like to use subscopes due to the following reasons:
* It reduces stack usage for variables that are only used in parts of the function. The stack is more limited in kernel-mode compared to user-space.
* It improves readability, since it restricts variable lifetime to only the parts of a function where they're used. You can think of this as a sort of "lightweight function".
* Reduced variable lifetime makes it easier to effectively utilize C++ destructors when appropriate.

**Comment by forderud** [comment]
@ManOnTheMountainTech Any more comments on the changes or are you ok with them?

File: TailLight/device.cpp [hunk 2]
```diff
@@ -19,6 +19,32 @@ VOID EvtSetBlackTimer(_In_ WDFTIMER  Timer) {
...
 }
 
+NTSTATUS EvtSelfManagedIoInit(WDFDEVICE device) {
+    // Initialize tail-light to black to have control over HW state
+    WDF_TIMER_CONFIG timerCfg = {};
+    WDF_TIMER_CONFIG_INIT(&timerCfg, EvtSetBlackTimer);
+
+    WDF_OBJECT_ATTRIBUTES attribs = {};
+    WDF_OBJECT_ATTRIBUTES_INIT(&attribs);
+    attribs.ParentObject = device;
```
Comment (ManOnTheMountainTech) [inline TailLight/device.cpp:29]: This keeps the object alive for as long as the device is alive. Can we shorten the lifetime of attribs down?

**Comment by ManOnTheMountainTech** [comment]
No further comments. Going forward there is some cleanup work to do.

File: TailLight/device.cpp (hunk 2 above)
Comment (forderud) [reply TailLight/device.cpp:29]: Not really. The driver also creates a queue for IOCTL processing, but it has the same lifetime as the device.

I though about deleting the timer object in the `EvtSetBlackTimer` callback, but that will according to the documentation lead to a [deadlock](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/wdftimer/nc-wdftimer-evt_wdf_timer#remarks). This can be worked around by scheduling a work item to delete the timer, but that sounds like a lot of complexity for little gain.

Comment (forderud) [reply TailLight/device.cpp:29]: Object cleanup would probably have been easier if we'd been able to replace the timer with a work item. However, my attempts on doing so have so far been unsuccessful.
